services:

    bulhi_monolog_db.log_handler:
        class: Bulhi\MonologDbBundle\Service\MonologHandlerService
        arguments: ['@doctrine', '@security.token_storage']

    bulhi_monolog_db.logentry_metadata_subscriber:
        class: Bulhi\MonologDbBundle\EventSubscriber\LogEntryMetadataSubscriber
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber, connection: default }